config_version = 14

[audio]
enable_sounds = false

[bar]
order = [ "ligmabar" ]

    [bar.ligmabar]
    background_opacity = 0.84999998100101948
    capsule = true
    capsule_padding = 4.0
    capsule_radius = 80
    capsule_thickness = 0.99999998137354851
    center = [ "group:g2" ]
    end = [ "group:g5", "tray", "group:g3", "group:g4", "group:g6" ]
    margin_ends = 0
    padding = 0
    panel_overlap = 0
    position = "left"
    radius = 0
    shadow = false
    start = [ "launcher", "group:g1", "media" ]
    widget_spacing = 8

        [[bar.ligmabar.capsule_group]]
        accordion = false
        accordion_direction = "end"
        enabled = true
        fill = "surface_variant"
        id = "g1"
        members = [ "notifications", "clock" ]
        opacity = 1.0
        padding = 4.0
        radius = 80.0

        [[bar.ligmabar.capsule_group]]
        accordion = false
        accordion_direction = "end"
        enabled = true
        fill = "surface_variant"
        id = "g2"
        members = [ "btn", "workspaces", "keybinds" ]
        opacity = 1.0
        padding = 4.0
        radius = 80.0

        [[bar.ligmabar.capsule_group]]
        accordion = false
        accordion_direction = "end"
        enabled = true
        fill = "surface_variant"
        id = "g3"
        members = [ "network", "bluetooth" ]
        opacity = 1.0
        padding = 4.0
        radius = 80.0

        [[bar.ligmabar.capsule_group]]
        accordion = false
        accordion_direction = "end"
        enabled = true
        fill = "surface_variant"
        id = "g4"
        members = [ "brightness", "volume" ]
        opacity = 1.0
        padding = 4.0
        radius = 80.0

        [[bar.ligmabar.capsule_group]]
        accordion = false
        accordion_direction = "end"
        enabled = true
        fill = "surface_variant"
        id = "g5"
        members = [ "wallpaper" ]
        opacity = 1.0
        padding = 4.0
        radius = 80.0

        [[bar.ligmabar.capsule_group]]
        accordion = false
        accordion_direction = "end"
        enabled = true
        fill = "surface_variant"
        id = "g6"
        members = [ "cat", "battery" ]
        opacity = 1.0
        padding = 4.0
        radius = 80.0

[calendar]
enabled = true
event_date_format = "%A %e %b"
refresh_minutes = 60

    [calendar.account.personal_google]
    type = "google"

[desktop_widgets]
enabled = false
schema_version = 2
widget_order = [ "desktop-widget-0000000000000002" ]

    [desktop_widgets.grid]
    cell_size = 32
    major_interval = 4
    visible = true

    [desktop_widgets.widget.desktop-widget-0000000000000002]
    box_height = 0.0
    box_width = 0.0
    cx = 1296.0
    cy = 75.0
    output = "eDP-1"
    placement_height = 960.0
    placement_width = 1440.0
    rotation = 0.0
    type = "clock"

        [desktop_widgets.widget.desktop-widget-0000000000000002.settings]
        background = true
        background_color = "surface"
        background_opacity = 0.80000000000000004
        background_padding = 10
        background_radius = 12
        center_text = true
        circle = true
        clock_style = "digital"
        color = "on_surface"
        font_family = ""
        format = "{:%H:%M}"
        shadow = true
        timezone = ""

[dock]
auto_hide = true
background_opacity = 0.84999998100101948
enabled = true
magnification_scale = 1.850000012665987
pinned = [ "firefox" ]
radius_top_left = 80
radius_top_right = 80
reserve_space = false
show_dots = true
show_instance_count = false

[location]
address = "Aalborg Øst"

[lockscreen]
fingerprint = false

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@DP-3", "lockscreen-login-box@WL-1", "lockscreen-login-box@eDP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-3"]
    box_height = 196.0
    box_width = 810.0
    cx = 1280.0
    cy = 1258.0
    output = "DP-3"
    placement_height = 1440.0
    placement_width = 2560.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-3".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@WL-1"]
    box_height = 196.0
    box_width = 720.0
    cx = 351.5
    cy = 778.0
    output = "WL-1"
    placement_height = 960.0
    placement_width = 703.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@WL-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 196.0
    box_width = 720.0
    cx = 720.0
    cy = 778.0
    output = "eDP-1"
    placement_height = 960.0
    placement_width = 1440.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[nightlight]
enabled = true
temperature_night = 3200

[notification]
history_retention_hours = 1

[plugin_settings."ezequiel/mango_layouts"]
list_mode = true
panel_position = "auto"

[plugin_settings."kenn/keybind-cheatsheet"]
cheatsheet_open_near_click = false
cheatsheet_position = "auto"
show_actions = true

[plugins]
auto_update = "official"
enabled = [
    "kenn/keybind-cheatsheet",
    "ezequiel/mango_layouts",
    "noctalia/kaomoji",
    "noctalia/example",
    "noctalia/notes",
    "dotnetrob/cat"
]

[shell]
external_ip_enabled = true
lang = "en"
telemetry_enabled = true

    [shell.animation]
    speed = 2.0000000298023224

    [shell.greeter_sync]
    auto_sync = true

[theme]
builtin = "Noctalia"
community_palette = "Oxocarbon"
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "faithful"

    [theme.templates]
    enable_builtin_templates = false
    enable_community_templates = false

[wallpaper]
directory = "/home/linde/Pictures/Wallpapers"
transition = [ "honeycomb" ]
transition_duration = 2000
transition_on_startup = true

    [wallpaper.default]
    path = "/home/linde/Pictures/Wallpapers/procedural_lighting_nebula_2k__wallpaper__by_validifyed_dfpxtfp.png"

    [wallpaper.last]
    path = "/home/linde/Pictures/Wallpapers/procedural_lighting_nebula_2k__wallpaper__by_validifyed_dfpxtfp.png"

    [wallpaper.monitors.DP-3]
    path = "/home/linde/Pictures/Wallpapers/procedural_lighting_nebula_2k__wallpaper__by_validifyed_dfpxtfp.png"

    [wallpaper.monitors.eDP-1]
    path = "/home/linde/Pictures/Wallpapers/bettergate.png"

[widget.audio_visualizer]
bands = 127
color_1 = "secondary"
mirrored = false
reversed = true
width = 296

[widget.brightness]
show_label = false

[widget.btn]
type = "ezequiel/mango_layouts:btn"

[widget.cat]
cat_color = "on_surface"
cat_color_mode = "custom"
type = "dotnetrob/cat:cat"

[widget.clock]
font_family = "Unifont"
font_scale = 1.24
format = "{:%H:\\n:%M\\n----UwU\\n----%d.\\n%b} "
timezone = "Europe/Copenhagen"
tooltip_format = "{:%H:\\n:%M\\n----UwU\\n----%d.\\n%b} "
vertical_format = "{:%H:\\n:%M\\n----UwU\\n----%d.\\n%b} "

[widget.keybinds]
type = "kenn/keybind-cheatsheet:keybinds"

[widget.launcher]
custom_image = "/home/linde/dotfiles/nixoslogo.png"
scale = 1.8

[widget.media]
hide_when_no_media = true

[widget.network]
show_label = false

[widget.volume]
show_label = false

[widget.workspaces]
hide_when_empty = true
labels_only_when_occupied = true