# many a borders here
borderpx=2d
#borderpx=0d
rootcolor=0x201b14ff
bordercolor=0x444444ff
dropcolor=0x8FBA7C55
splitcolor=0xEB441EFF

focuscolor=0xc9b890ff
#focuscolor=0xff0000ff



maximizescreencolor=0x89aa61ff
urgentcolor=0xad401fff
scratchpadcolor=0x516c93ff
globalcolor=0xb153a7ff
overlaycolor=0x14a57cff


# Appearance
gappih=5 # 5
gappiv=5 # 5
gappoh=10 # 10
gappov=19 # 19

#gappih=5 # 5
#gappiv=5 # 5
#gappoh=0 # 10
#gappov=0 # 19
