# Brightness controls, requires brightnessctl
# 9% is the lowest it can go
bind=NONE,XF86MonBrightnessUp,spawn,brightnessctl s +5%
bind=SHIFT,XF86MonBrightnessUp,spawn,brightnessctl s 100%
bind=NONE,XF86MonBrightnessDown,spawn,brightnessctl s 5%-
bind=SHIFT,XF86MonBrightnessDown,spawn,brightnessctl s 0%

#bind=NONE,XF86MonBrightnessUp,spawn,brightnessctl set +5%
#bind=NONE,XF86MonBrightnessDown,spawn,brightnessctl set 5%-

# Audio controls, requires wpctl
bind=NONE,XF86AudioRaiseVolume,spawn,wpctl set-volume -l 1.5 @DEFAULT_AUDIO_SINK@ 5%+
bind=NONE,XF86AudioLowerVolume,spawn,wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bind=NONE,XF86AudioMute,spawn,wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

# Chad monitor controls
#bind=SUPER,XF86AudioMute,spawn, mmsg dispatch toggle_monitor,eDP-1
bind=SUPER,XF86AudioMute,spawn, mmsg dispatch sleep_toggle_monitor,eDP-1,eDP-1

# Player controls, requires playerctl
bind=NONE,XF86AudioNext,spawn,playerctl next
bind=NONE,XF86AudioPrev,spawn,playerctl previous
bind=NONE,XF86AudioPlay,spawn,playerctl play-pause
